########## Auto Generated by cfg ##########
######### Do not modify this part #########
if [ -n "$BASH_VERSION" ]; then
        # include .bashrc if it exists
        if [ -f "$HOME/.bashrc" ]; then
                . "$HOME/.bashrc"
        fi
fi
###########################################
